miracle-job-a/company-service

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/repository/CompanyRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java, src/main/java/com/miracle/companyservice/util/filter/TokenCheckFilter.java, src/main/java/com/miracle/companyservice/util/interceptor/AuthorizationInterceptor.java, src/test/java/com/miracle/companyservice/service/CompanyServiceImplTest.java
=> Feature interceptor

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/dto/request/PostRequestDto.java, src/main/java/com/miracle/companyservice/dto/request/QuestionRequestDto.java, src/main/java/com/miracle/companyservice/entity/Question.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/repository/QuestionRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
ex) feature_post-edit -> feature
- 공고 수정 API 구현
- 공고 수정 시, 자소서 문항 수정/등록 기능 구현
- API URL 매핑과 URL 수정
- 서비스 메서드 응답 수정
=> Feature post edit

src/main/java/com/miracle/companyservice/controller/swagger/ApiDeleteFaq.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiGetDeadlinePosts.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiGetFaq.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
refactor_kade -> feature
- 마감임박순 정렬시, 마감된 공고가 보이지 않아 postRespository의 쿼리 수정
- deleteFaq, getFaq의 불필요한 companyId 인증 코드 삭제
=> Refactor kade

src/test/java/com/miracle/companyservice/repository/CompanyRepositoryTest.java
test_companyRepository -> feature
- 인터셉터에서 사용하는 회원 인증메서드 테스트 코드 작성
- 기업아이디로 기업이미지 조회하는 메서드 테스트 코드 작성
=> Test: 회원인증 테스트, 기업이미지 가져오기 테스트 완료

build.gradle, src/test/java/com/miracle/companyservice/repository/CompanyFaqRepositoryTest.java, src/test/resources/application.yml
###Test
[x] CompanyFaqRepository 테스트 코드 구현
###반영 브랜치
test_companyFaqRepository -> feature
###변경 사항
- 각 테스트 후, h2 DB 시퀀스 1부터 시작되도록 세팅
- save() 메서드 테스트 구현
- countByCompanyId() 메서드 테스트 구현
- existsByCompanyIdAndId() 메서드 테스트 구현
- deleteById() 테스트 구현
=> Test company faq repository

src/test/java/com/miracle/companyservice/repository/BnoRepositoryTest.java
test_bnoRepository -> feature
- 테스트 DB -> h2로 변경
- 각 메서드 종료 후, 시퀀스 1부터 시작하도록 세팅
- 기존 구현 메서드 h2에 맞게 변경
=> Test: BnoRepository 테스트 코드 수정

src/main/java/com/miracle/companyservice/repository/CompanyRepository.java, src/test/java/com/miracle/companyservice/repository/CompanyRepositoryTest.java
test_companyRepository -> feature
1. h2 DB로 변경
2. 각 메서드 테스트 종료 후, 시퀀스 1부터 시작하도록 세팅
3. 기존 구현 메서드 수정
4. CompanyRepository의 불필요한 메서드 삭제
=> Test company repository

src/main/java/com/miracle/companyservice/entity/BaseEntity.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java, src/test/java/com/miracle/companyservice/repository/PostRepositoryTest.java
test_PostRepository -> feature
- 최신공고 3건 반환 쿼리의 now 삭제
- 마감임박순 정렬 쿼리의 now 삭제
- PostRepository 테스트 코드 작성
=> Test post repository

src/main/java/com/miracle/companyservice/repository/BnoRepository.java
=> Comment: 메서드 주석 추가

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java
=> Fix interceptor path

src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/dto/request/PostRequestDto.java, src/main/java/com/miracle/companyservice/dto/request/QuestionRequestDto.java, src/main/java/com/miracle/companyservice/exception/ExceptionController.java, src/main/java/com/miracle/companyservice/util/interceptor/AuthorizationInterceptor.java
ex) feature_refactor -> feature
- postRequestDto, questionRequestDto 유효성 검사 추가
- ExceptionController 유효성 검사에 따른 오류 코드 지정
- companyControlller @vaild 추가
=> Feature refactor

src/main/java/com/miracle/companyservice/config/SwaggerConfig.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiAddFaq.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/util/interceptor/AuthorizationInterceptor.java
feature_swaggerAndInterceptor-> feature
=> Feature swagger and interceptor

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiGetCompany.java, src/main/java/com/miracle/companyservice/dto/response/CompanyPageResponseDto.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
ex) feature_post-companyPage -> feature
=> Feature company page

src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/dto/request/CompanyFaqRequestDto.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java, src/main/java/com/miracle/companyservice/util/encryptor/PasswordEncryptor.java, src/test/java/com/miracle/companyservice/service/CompanyServiceImplTest.java
refactor_duplicatedData -> feature
=> Refactor duplicated data

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/dto/request/ConditionalSearchPostRequestDto.java, src/main/java/com/miracle/companyservice/dto/response/ConditionalSearchPostResponseDto.java, src/main/java/com/miracle/companyservice/dto/response/MainPagePostsResponseDto.java, src/main/java/com/miracle/companyservice/dto/response/ManagePostsResponseDto.java, src/main/java/com/miracle/companyservice/dto/response/PostResponseDto.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java, src/main/java/com/miracle/companyservice/util/specification/PostSpecifications.java, src/test/java/com/miracle/companyservice/service/CompanyServiceImplTest.java
feature_conditionalSearch -> feature
- 공고 조건 검색 구현을 위한 Specification
=> Feature conditional search

src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiConditionalSearch.java, src/main/java/com/miracle/companyservice/dto/request/ConditionalSearchPostRequestDto.java, src/main/java/com/miracle/companyservice/exception/ExceptionController.java
=> Feat swagger

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiConditionalSearch.java, src/main/java/com/miracle/companyservice/dto/request/ConditionalSearchPostRequestDto.java, src/main/java/com/miracle/companyservice/dto/response/ConditionalSearchPostResponseDto.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
=> Feat page edit

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/exception/ExceptionController.java
=> Fix interceptor

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java, src/main/java/com/miracle/companyservice/util/encryptor/Encryptors.java, src/main/java/com/miracle/companyservice/util/interceptor/GetMethodInterceptor.java, src/test/java/com/miracle/companyservice/repository/PostRepositoryTest.java, src/test/java/com/miracle/companyservice/service/CompanyServiceImplTest.java
=> Fix manage posts

src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiQuitCompany.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
=> Feat quit company

src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiUserCheck.java, src/main/java/com/miracle/companyservice/repository/CompanyRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
ex) feature_userCheck-> feature
=> Feature user check

src/main/java/com/miracle/companyservice/util/encryptor/Encryptors.java
=> Refactor: 예외 오타 수정

src/main/java/com/miracle/companyservice/dto/response/ConditionalSearchPostResponseDto.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
=> Fix: 상세검색 시 사진 반환 요청에 따른 수정

src/main/java/com/miracle/companyservice/controller/swagger/ApiRegisterPost.java, src/main/java/com/miracle/companyservice/dto/request/CompanyFaqRequestDto.java, src/main/java/com/miracle/companyservice/dto/request/PostRequestDto.java, src/main/java/com/miracle/companyservice/dto/request/QuestionRequestDto.java
- 유효성 검사 오류 발생에 따른 코드 수정
fix -> feature
=> Fix: 유효성 검사 오류 발생에 따른 코드 수정

build.gradle, src/main/java/com/miracle/companyservice/CompanyServiceApplication.java, src/main/resources/application.yml, src/main/resources/application1.md
feat_eureka_config -> feature
=> Feat eureka config

src/main/java/com/miracle/companyservice/dto/request/PostRequestDto.java, src/main/java/com/miracle/companyservice/exception/ExceptionController.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
=> Fix: 유효성 검사 오류에 따른 리팩토링

src/main/resources/application.yml
- ec2 적용위한 application.yml 수정
- feat_ec2 -> feature
=> Feat: ec2 저장위해 application.yml 수정

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiGetCompanyName.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
feature_return-companyName -> feature
=> Feature return company name

src/main/java/com/miracle/companyservice/util/encryptor/Encryptors.java, src/main/resources/application1.md
=> Fix: 암호화 키 config로 이동

src/main/java/com/miracle/companyservice/dto/response/MainPagePostsResponseDto.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java, src/test/java/com/miracle/companyservice/service/CompanyServiceImplTest.java
=> Fix: 메인페이지 공고의 기업명 추가 요청에 따른 로직 수정

src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
=> Feat: 기업 승인 레포지토리 save 기능 추가

src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/dto/response/AlertResponseDto.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
- 코딩테스트 (MZ공고) 알림용 정보 반환 기능 추가
=> Feat alert

build.gradle, src/main/java/com/miracle/companyservice/config/Config.java
- Acutator / Prometheus 추가
feat_prometheus -> feature
=> Feat prometheus

src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiCheckPostAuthority.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiPostsInfoForTestAlert.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiSignUp.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
- 공고 등록 가능 여부 확인 API 구현
- 테스트 알림위한 공고조회 메서드의 swagger 명세
- Fix: 회원 가입 시, 실패 로직 추가
feat_blockPosting -> feature
=> Feat block posting

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiCheckClosedPost.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiCheckPostStatus.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiCountWholePosts.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
feature_whole-post-count -> feature
=> Feature whole post count / status

src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
- 테스트 알림시간 계산 로직 수정
- feat_schedule -> feature
=> Feat: 테스트 알림 시간 로직 수정

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiRegisterPost.java, src/main/java/com/miracle/companyservice/dto/request/PostRequestDto.java, src/main/java/com/miracle/companyservice/dto/response/PostInsightResponseDto.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
feature_today-posted-list -> feature
=> Feature today posted list

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
=> Feature today post

src/main/java/com/miracle/companyservice/config/WebMvcConfig.java, src/main/java/com/miracle/companyservice/controller/CompanyController.java, src/main/java/com/miracle/companyservice/controller/swagger/ApiGetJobStacks.java, src/main/java/com/miracle/companyservice/dto/response/JobStackInsightResponseDto.java, src/main/java/com/miracle/companyservice/repository/PostRepository.java, src/main/java/com/miracle/companyservice/service/CompanyService.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
feature_jobStackList -> feature
=> Feature job stack list

src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java
refactor -> feature
- 공고 전체 조회 결과가 없을 때 또한 그 데이터가 차트에 반영되어야 하기 때문에 예외 처리 제거
=> Fix: 예외처리 수정/추가

src/main/java/com/miracle/companyservice/dto/request/AccessToken.java, src/main/java/com/miracle/companyservice/service/CompanyServiceImpl.java, src/main/java/com/miracle/companyservice/service/TokenService.java, src/main/java/com/miracle/companyservice/service/TokenServiceImpl.java, src/main/java/com/miracle/companyservice/util/filter/RequestFilter.java, src/main/java/com/miracle/companyservice/util/filter/TokenFilter.java
=> Feat token filter
